//
// Created by Hans Johnson on 2026-02-14.
//

#include "GaussianCLP.h" // <-- NOTE THIS FILE WAS AUTO GENERATED by GENERATECLP()

// itk
#include <itkRecursiveGaussianImageFilter.h>
#include <itkImageFileWriter.h>
#include <itkImageFileReader.h>

int main (int argc, char * argv[])
{
  PARSE_ARGS;

  std::cout << "The input volume is: " << inputVolume << std::endl;
  std::cout << "The output volume is: " << outputVolume << std::endl;

  using PixelType = short;
  constexpr int Dimension = 3;
  using ImageType = itk::Image<PixelType, Dimension>;

  using ReaderType = itk::ImageFileReader<ImageType>;
  auto reader = ReaderType::New();

  reader->SetFileName(inputVolume);

  using FilterType = itk::RecursiveGaussianImageFilter<ImageType, ImageType>;
  auto filter = FilterType::New();
  filter->SetSigma(sigma);
  filter->SetInput(reader->GetOutput());

  using WriterType = itk::ImageFileWriter<ImageType>;
  auto writer = WriterType::New();

  writer->SetInput(filter->GetOutput());
  writer->SetFileName(outputVolume);

  try {
    writer->Update();
  }
  catch(const itk::ExceptionObject e){
    std::cout << "I DONT WORK AHHH ITS BECAUSE: " << e << std::endl;
    return EXIT_FAILURE;
  }

  return EXIT_SUCCESS;
}
