//
// Created by Hans Johnson on 2026-02-14.
//

#include "SimpleThresholdCLP.h" // <-- NOTE THIS FILE WAS AUTO GENERATED by GENERATECLP()

// itk
#include <itkBinaryThresholdImageFilter.h>
#include <itkImageFileWriter.h>
#include <itkImageFileReader.h>

int main (int argc, char * argv[])
{
  PARSE_ARGS;  // <--- This is always the first line and is defined in SimpleThresholdCLP.h
  std::cout << "The input volume is: " << inputVolume << std::endl;
  std::cout << "The output volume is: " << outputVolume << std::endl;

  if(lowThreshold >= highThreshold){
    std::cout << "Low threshold (" << lowThreshold << ") is greater than or equal to high threshold (" << highThreshold << ")" << std::endl;
    return EXIT_FAILURE;
  }

  using PixelType = short;
  constexpr int Dimension = 3;
  using ImageType = itk::Image<PixelType, Dimension>;

  using ReaderType = itk::ImageFileReader<ImageType>;
  auto reader = ReaderType::New();

  reader->SetFileName(inputVolume);

  using ThresholdType = itk::BinaryThresholdImageFilter<ImageType, ImageType>;
  auto threshold = ThresholdType::New();
  threshold->SetInsideValue(insideValue);
  threshold->SetOutsideValue(outsideValue);
  threshold->SetLowerThreshold(lowThreshold);
  threshold->SetUpperThreshold(highThreshold);
  threshold->SetInput(reader->GetOutput());

  using WriterType = itk::ImageFileWriter<ImageType>;
  auto writer = WriterType::New();

  writer->SetInput(threshold->GetOutput());
  writer->SetFileName(outputVolume);

  try {
    writer->Update();
  }
  catch(const itk::ExceptionObject e){
    std::cout << "I DONT WORK AHHH ITS BECAUSE: " << e << std::endl;
    return EXIT_FAILURE;
  }

  return EXIT_SUCCESS;
}
