//
// Created by Hans Johnson on 2026-02-14.
//

#include "DOGCLP.h" // <-- NOTE THIS FILE WAS AUTO GENERATED by GENERATECLP()

// itk
#include <itkRecursiveGaussianImageFilter.h>
#include <itkImageFileWriter.h>
#include <itkImageFileReader.h>
#include <itkSubtractImageFilter.h>

int main (int argc, char * argv[])
{
  PARSE_ARGS;

  std::cout << "The input volume is: " << inputVolume << std::endl;
  std::cout << "The output volume is: " << outputVolume << std::endl;
  std::cout << "sigma 1: " << sigma1 << std::endl;
  std::cout << "sigma 2: " << sigma2 << std::endl;

  if(sigma1 == sigma2){
    std::cout << "sigma1 (" << sigma1 << ") and sigma2 (" << sigma2 <<") cannot be equal" << std::endl;
    return EXIT_FAILURE;
  }

  using PixelType = short;
  constexpr int Dimension = 3;
  using ImageType = itk::Image<PixelType, Dimension>;

  using ReaderType = itk::ImageFileReader<ImageType>;
  auto reader = ReaderType::New();

  reader->SetFileName(inputVolume);

  using FilterType = itk::RecursiveGaussianImageFilter<ImageType, ImageType>;

  auto filter1 = FilterType::New();
  filter1->SetSigma(sigma1);
  filter1->SetInput(reader->GetOutput());

  auto filter2 = FilterType::New();
  filter2->SetSigma(sigma2);
  filter2->SetInput(reader->GetOutput());

  using SubtractFilterType = itk::SubtractImageFilter<ImageType, ImageType, ImageType>;
  SubtractFilterType::Pointer subtract = SubtractFilterType::New();
  subtract->SetInput1(filter1->GetOutput());
  subtract->SetInput2(filter2->GetOutput());

  using WriterType = itk::ImageFileWriter<ImageType>;
  auto writer = WriterType::New();

  writer->SetInput(subtract->GetOutput());
  writer->SetFileName(outputVolume);

  try {
    writer->Update();
  }
  catch(const itk::ExceptionObject e){
    std::cout << "I DONT WORK AHHH ITS BECAUSE: " << e << std::endl;
    return EXIT_FAILURE;
  }

  return EXIT_SUCCESS;
}
